repo:
  description: "Auto-updated curated list of GitHub CLI extensions"
  homepage: ""
  visibility: public
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_squash_merge: true
  delete_branch_on_merge: true

topics:
  - awesome-list
  - github-cli
  - cli
  - github

labels:
  replace_default: true
  items:
    - name: automated
      color: "0e8a16"
      description: Automated updates
    - name: documentation
      color: "0075ca"
      description: Documentation updates

branch_protection:
  main:
    required_reviews: 1
    dismiss_stale_reviews: false
    require_status_checks: true
    status_checks:
      - check
    strict_status_checks: true
    enforce_admins: false
    allow_force_pushes: false
    allow_deletions: false

actions:
  enabled: true
  allowed_actions: all
  default_workflow_permissions: write
  can_approve_pull_request_reviews: true

pages:
  build_type: workflow
